config/routes.rb
Rails.application.routes.draw do
  resources :products, only: [:index, :show] do
    resources :categories, only:[:show]
  end



  get 'regulatious'=> 'static#terms', as: :regulations
  get 'privacy-policy'=> 'static#privacy', as: :privacy_policy
  get 'delivery'=> 'static#shipping', as: :delivery
  get 'about'=> 'static#about', as: :about


  root'products#index'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  validates :name , presence:true


  def to_param
    "#{id}-#{name}".parameterize
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  validates :name , presence:true
  validates :description , presence:true
  validates :price , numericality: {grather_than: 0.0}
  validates :category , presence:true
   mount_uploader :photo, ProductPhotoUploader

   def to_param
     "#{id}-#{name}".parameterize
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
@category=Category.find(params[:id])
@product=@category.products.page(params[:page]).per(6)
end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @product=Product.all.order(created_at: :desc).limit(9)
    @products=@product.page(params[:page]).per(6)


  end

  def show
    @product=Product.find(params[:id])
    @category=@product.category

  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def terms
  end

  def privacy
  end

  def shipping
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/categories/show.html.erb
<h1> <%=@category.name%></h1>


<%=render partial: 'products/products'%>

<%= paginate @product %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

    <title>Shop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <a div class="navbar-brand" href="<%=root_path%>"> SHOP </a>
            </div>
          <ul class="nav navbar-nav">
            <li class="nav-item"> <%= link_to "Start",root_path %></li>
            <li class="nav-item"> <%= link_to "Regulatious",regulations_path %> </li>
            <li class="nav-item"> <%= link_to "Privacy policy",privacy_policy_path %></li>
            <li class="nav-item"> <%= link_to "Delivery",delivery_path %> </li>
            <li class="nav-item"> <%= link_to "About",about_path %> </li>
          </ul>
        </div>
      </nav>
      <div class="container-fluid">
          <div class="row">
            <div class="col-md-2">
              <h3>Categories</h3>
        <ul class="nav nav-slidebar">

          <% Category.all.each do |category| %>
            <li<%if @category==category%> class="active"<%end%>>
              <%=link_to category.name, product_category_path(category,category) %>
            </li>
            <%end%>
        </ul>
        </div>
          <div class="col-md-10">
              <%= yield %>
            </div>
        </div>
      </div>

  </body>
</html>

app/views/products/_products.html.erb
<% @product.each_slice(3) do |slice|%>
  <div class="row">
    <% slice.each do |product|%>
      <div class="col-md-4">
        <div class="thumbnail">

          <%=link_to product_path(product) do %>
          <%= image_tag Faker::Placeholdit.image("640x480", 'jpg')%>
          <%end%>


          <div class="caption">
            <h3><%=link_to  product.name , product_category_path(product,product) %></h3>
            <p><%= product.description %></p>
            <p><%= product.price %></p>
          </div>
          <%= link_to "#", class:"btn btn-primary" do %>
          <span class="fa fa-shopping-cart"> Add to shopping cart</span>

          <%end%>
          </div>
      </div>
   <%end%>
 </div>
<%end%>

app/views/products/index.html.erb
<h1>Top products</h1>

<%= render partial:'products'%>

<%= paginate @products %>

app/views/products/show.html.erb
<div class="jumbotron">
<div class="container-fluid">
  <div class="row">
      <div class="col-md-5">
        <h1><%=@product.name%></h1>
        <p class="lead"><%=@product.description%></p>
          <%=@product.long_description%>


        <p class="lead"><%=@product.price%></p>
          <p>
          <%= link_to "#", class:"btn btn-primary" do %>
          <span class="fa fa-shopping-cart"> Add to shopping cart</span>
          <%end%>
          </p>
        </div>

        <div class="col-md-7">
          <%= image_tag Faker::Placeholdit.image("640x480", 'jpg'),class: "img-responsive"%>
        </div>

      </div>
    </div>
  </div>
  </div>